language: android
jdk: oraclejdk8
dist: precise
cache: npm
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - build-tools-26.0.3
    - build-tools-27.0.3
    - build-tools-28.0.3
    - android-25
    - android-26
    - android-27
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
before_install:
  - nvm install 11
  - node --version
install:
  - npm install
  - npm install -g react-native-cli
script:
  - cd examples
  - react-native init --version="$RN_VERSION" Setup
  - bash applyPatches.sh $RN_VERSION
  - cd Setup
  - npm install -S ../..
  - react-native link react-native-ble-plx
  - cd android
  - ./gradlew assemble

env:
  - RN_VERSION=0.53.0
  - RN_VERSION=0.54.0
  - RN_VERSION=0.55.0
  - RN_VERSION=0.56.1
  - RN_VERSION=0.57.2
  - RN_VERSION=0.57.5
  - RN_VERSION=0.57.8
  - RN_VERSION=0.58.0
  - RN_VERSION=0.58.3
