language: node_js
cache: npm
node_js:
  - 11
  - 10
  - 8
script:
  - npm run lint
  - npm test

matrix:
  include:
    - language: android
      jdk: oraclejdk8
      dist: precise
      node_js: false
      android:
        components:
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-27
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-android-support
        licenses:
          - 'android-sdk-license-.+'
      script:
        - cd android
        - chmod +x gradlew
        - ./gradlew assembleRelease test

    - language: objective-c
      os: osx
      osx_image: xcode10.1
      node_js: 10
      cache:
        - npm
        - yarn
      install:
        - npm install
        - npm install -g yarn
        - yarn --cwd examples/Barebone
      script:
        - cd examples/Barebone
        - RCT_NO_LAUNCH_PACKAGER=true xcodebuild -scheme Barebone -project ios/Barebone.xcodeproj -sdk iphonesimulator -quiet -UseModernBuildSystem=NO
    - language: android
      jdk: oraclejdk8
      dist: precise
      node_js: 11
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.2
          - android-28
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-android-support
        licenses:
          - 'android-sdk-license-.+'
      install:
        - npm install
      script:
        - cd examples
        - react-native init Setup
        - cd Setup
        - npm install -S ../..
        - react-native link react-native-ble-plxx
        - cd android
        - ./gradlew assemble
