matrix:
  include:
    - language: node_js
      node_js: 8
      script:
        - npm install
        - npm run lint
        - npm test

    - language: android
      jdk: oraclejdk8
      dist: precise
      node_js: false
      android:
        components:
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-27
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-android-support
        licenses:
          - 'android-sdk-license-.+'
      script:
        - cd android
        - chmod +x gradlew
        - ./gradlew assembleRelease test

    - language: objective-c
      os: osx
      osx_image: xcode10.1
      node_js: 8
      xcode_project: examples/Barebone/ios/Barebone.xcodeproj
      install:
        - npm install
      script:
        - cd examples/Barebone
        - npm install
        - RCT_NO_LAUNCH_PACKAGER=true xcodebuild -scheme Barebone -project ios/Barebone.xcodeproj -sdk iphonesimulator -quiet -UseModernBuildSystem=NO
