name: Setup
description: Setup Node.js and install dependencies
inputs:
  REACT_NATIVE_VERSION:
    description: React Native version to use
    required: false
  NODE_VERSION:
    description: Node version to use # https://github.com/actions/setup-node#supported-version-syntax
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}

    - name: Initialize project template
      run: npx react-native@latest init BlePlxExample --verbose --version ${{ inputs.REACT_NATIVE_VERSION }} --directory test_project --skip-install --verbose
      shell: bash

    - name: Cache dependencies
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ inputs.REACT_NATIVE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.REACT_NATIVE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.os }}-${{ inputs.REACT_NATIVE_VERSION }}-yarn-

    - name: Copy project files
      run: node ./scripts/copyExampleProjectFiles.js
      shell: bash

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: |
        yarn install --cwd test_project
        yarn install
      shell: bash
